// This code conforms with the UFC specification version 2018.1.0
// and was automatically generated by FFC version 2019.1.0.
//
// This code was generated with the following parameters:
//

//  add_tabulate_tensor_timing:     False
//  convert_exceptions_to_warnings: False
//  cpp_optimize:                   True
//  cpp_optimize_flags:             '-O2'
//  epsilon:                        1e-14
//  error_control:                  False
//  external_include_dirs:          ['/home/simon/anaconda3/envs/fenics_old/include', 
//                                  '/home/simon/anaconda3/envs/fenics_old/include/eig
//                                  en3', '/home/simon/anaconda3/envs/fenics_old/inclu
//                                  de']
//  external_includes:              ''
//  external_libraries:             ''
//  external_library_dirs:          ''
//  form_postfix:                   False
//  format:                         'ufc'
//  generate_dummy_tabulate_tensor: False
//  max_signature_length:           0
//  no-evaluate_basis_derivatives:  True
//  optimize:                       True
//  precision:                      None
//  quadrature_degree:              None
//  quadrature_rule:                None
//  representation:                 'auto'
//  split:                          False

#ifndef __FFC_FORM_F5C58D5ED09C5F47CDBCD21502D3BD27F46BFB05_H
#define __FFC_FORM_F5C58D5ED09C5F47CDBCD21502D3BD27F46BFB05_H
#include "ffc_coordinate_mapping_fdf65ad1b4ee585aa7f358c9d8ed7cd18fb0ebf8.h"
#include "ffc_element_b6056e9c39d9d0154897eac8d86c6d3a5d1f55b9.h"
#include "ffc_element_d813efd86d1269ffed6166a5f2febcbe484faa4d.h"
#include "ffc_element_de8439ade25e15ca5629b7c8b5e041c4eaec6481.h"
#include <algorithm>
#include <cmath>
#include <iostream>
#include <stdexcept>
#include <ufc.h>

class ffc_form_f5c58d5ed09c5f47cdbcd21502d3bd27f46bfb05_cell_integral_main_11: public ufc::cell_integral
{
public:

  ffc_form_f5c58d5ed09c5f47cdbcd21502d3bd27f46bfb05_cell_integral_main_11();

  ~ffc_form_f5c58d5ed09c5f47cdbcd21502d3bd27f46bfb05_cell_integral_main_11() override;

  const std::vector<bool> & enabled_coefficients() const final override;

  void tabulate_tensor(double * A,
                       const double * const * w,
                       const double * coordinate_dofs,
                       int cell_orientation) const final override;

};

extern "C" ufc::cell_integral * create_ffc_form_f5c58d5ed09c5f47cdbcd21502d3bd27f46bfb05_cell_integral_main_11();


class ffc_form_f5c58d5ed09c5f47cdbcd21502d3bd27f46bfb05_form_main: public ufc::form
{
public:

  ffc_form_f5c58d5ed09c5f47cdbcd21502d3bd27f46bfb05_form_main();

  ~ffc_form_f5c58d5ed09c5f47cdbcd21502d3bd27f46bfb05_form_main() override;

  const char * signature() const final override;

  std::size_t rank() const final override;

  std::size_t num_coefficients() const final override;

  std::size_t original_coefficient_position(std::size_t i) const final override;

  ufc::finite_element * create_coordinate_finite_element() const final override;

  ufc::dofmap * create_coordinate_dofmap() const final override;

  ufc::coordinate_mapping * create_coordinate_mapping() const final override;

  ufc::finite_element * create_finite_element(std::size_t i) const final override;

  ufc::dofmap * create_dofmap(std::size_t i) const final override;

  std::size_t max_cell_subdomain_id() const final override;

  std::size_t max_exterior_facet_subdomain_id() const final override;

  std::size_t max_interior_facet_subdomain_id() const final override;

  std::size_t max_vertex_subdomain_id() const final override;

  std::size_t max_custom_subdomain_id() const final override;

  std::size_t max_cutcell_subdomain_id() const final override;

  std::size_t max_interface_subdomain_id() const final override;

  std::size_t max_overlap_subdomain_id() const final override;

  bool has_cell_integrals() const final override;

  bool has_exterior_facet_integrals() const final override;

  bool has_interior_facet_integrals() const final override;

  bool has_vertex_integrals() const final override;

  bool has_custom_integrals() const final override;

  bool has_cutcell_integrals() const final override;

  bool has_interface_integrals() const final override;

  bool has_overlap_integrals() const final override;

  ufc::cell_integral * create_cell_integral(std::size_t i) const final override;

  ufc::exterior_facet_integral * create_exterior_facet_integral(std::size_t i) const final override;

  ufc::interior_facet_integral * create_interior_facet_integral(std::size_t i) const final override;

  ufc::vertex_integral * create_vertex_integral(std::size_t i) const final override;

  ufc::custom_integral * create_custom_integral(std::size_t i) const final override;

  ufc::cutcell_integral * create_cutcell_integral(std::size_t i) const final override;

  ufc::interface_integral * create_interface_integral(std::size_t i) const final override;

  ufc::overlap_integral * create_overlap_integral(std::size_t i) const final override;

  ufc::cell_integral * create_default_cell_integral() const final override;

  ufc::exterior_facet_integral * create_default_exterior_facet_integral() const final override;

  ufc::interior_facet_integral * create_default_interior_facet_integral() const final override;

  ufc::vertex_integral * create_default_vertex_integral() const final override;

  ufc::custom_integral * create_default_custom_integral() const final override;

  ufc::cutcell_integral * create_default_cutcell_integral() const final override;

  ufc::interface_integral * create_default_interface_integral() const final override;

  ufc::overlap_integral * create_default_overlap_integral() const final override;

};

extern "C" ufc::form * create_ffc_form_f5c58d5ed09c5f47cdbcd21502d3bd27f46bfb05_form_main();

#endif
